import os
from pathlib import Path
import math
import time
import threading
import warnings
import numpy as np
from pynput import keyboard, mouse

from capture_images import take_screenshot, process_screenshot
from perception import perceive
from execute_action import PLACEMENT_TILES, tile_to_screen, ARENA_TOP_LEFT, ARENA_PIXEL_W, ARENA_PIXEL_H, DISPLAY_SCALE

warnings.filterwarnings("ignore", message=".*pin_memory.*", category=UserWarning) # get rid of annoying warning


# ----- CONFIG -----

STATES_DIR = "human_data/states"
ACTIONS_DIR = "human_data/actions"
WAIT_ACTION = 32
RECORD_INTERVAL = 1.0

# Precompute screen pixel coords for each placement tile
TILE_SCREEN_COORDS = [tile_to_screen(r, c) for r, c in PLACEMENT_TILES]


# ----------

def nearest_tile(x, y):
    """Cast mouse click to closest of 8 valid tile placements"""
    return int(np.argmin([math.dist((x, y), t) for t in TILE_SCREEN_COORDS]))


def init_counter() -> int:
    existing = Path(STATES_DIR).glob("?????.npz")
    numbers = [int(p.stem) for p in existing]

    # Insert gap so first state of session is non-consecutive (for human data loading)
    return max(numbers, default=-1) + 1


if __name__ == "__main__":
    os.makedirs(STATES_DIR, exist_ok=True)
    os.makedirs(ACTIONS_DIR, exist_ok=True)

    lock = threading.Lock() # prevent race conditions

    tracking = {
        "current_state": None, # state ID of the last unpaired state
        "action_key": None, # most recent 1-4 key press
        "state_counter": init_counter(),
        "session_states": 0,
        "session_actions": 0,
        "last_was_match": False, # track whether last screen watch "match"
    }

    print(f"Resuming from state {tracking['state_counter']}, starting in 5 sec")
    time.sleep(5)
    print("Recording, Ctrl+C to stop")

    def on_key_press(key):
        """Record 1-4 key press (card select)"""
        try:
            if key.char in ['1', '2', '3', '4']:
                with lock:
                    tracking["action_key"] = int(key.char)
                print(f"Key {key.char}")
        except AttributeError: # "special" keys don't have .char yeesh
            pass

    def on_click(x, y, button, pressed):
        """Record action to nearest state (click comes last -> need both state and action key)"""
        if not pressed:
            return
        # print(f"CLICK_MAP coord: ({x}, {y})")

        # Adjust for mac display
        px, py = x * DISPLAY_SCALE, y * DISPLAY_SCALE
        # Ignore synthetic clicks generated by emulator key mappings (which are outside arena bounds)
        if not (ARENA_TOP_LEFT[0] <= px <= ARENA_TOP_LEFT[0]+ARENA_PIXEL_W) and (ARENA_TOP_LEFT[1] <= py <= ARENA_TOP_LEFT[1]+ARENA_PIXEL_H):
            return
        tile_idx = nearest_tile(px, py)
        with lock:
            state_id = tracking["current_state"]
            action_key = tracking["action_key"]
            if state_id is not None and action_key is not None:
                action_idx = ((action_key-1) * 8) + tile_idx # 0-31
                action_path = os.path.join(ACTIONS_DIR, f"{state_id:05d}.npy")
                np.save(action_path, np.array(action_idx, dtype=np.int32))
                tracking["session_actions"] += 1
                tracking["current_state"] = None
                tracking["action_key"] = None
                print(f"Action {action_idx} (card {action_key}, tile {tile_idx}) -> state {state_id:05d}")

    keyboard_listener = keyboard.Listener(on_press=on_key_press)
    mouse_listener = mouse.Listener(on_click=on_click)
    keyboard_listener.start()
    mouse_listener.start()

    try:
        while True:
            ss = take_screenshot()
            crops = process_screenshot(ss)
            screen_name, troop_tensor, flat_vector = perceive(crops)

            if screen_name == "match":
                with lock:
                    old_state_id = tracking["current_state"]

                    # If we perceived new state before action came in, record that state's action as "wait"
                    if old_state_id is not None:
                        action_path = os.path.join(ACTIONS_DIR, f"{old_state_id:05d}.npy")
                        np.save(action_path, np.array(WAIT_ACTION, dtype=np.int32))
                        tracking["session_actions"] += 1
                        print(f"Action 32 (wait) -> state {old_state_id:05d}")

                    # Insert a gap when entering a new match (for human data loader non-consecutive)
                    if not tracking["last_was_match"]:
                        tracking["state_counter"] += 1
                    tracking["state_counter"] += 1

                    # Can always record state
                    state_id = tracking["state_counter"]
                    state_path = os.path.join(STATES_DIR, f"{state_id:05d}.npz")
                    np.savez_compressed(state_path, troop_tensor=troop_tensor, flat_vector=flat_vector)

                    tracking["session_states"] += 1
                    tracking["current_state"] = state_id
                    tracking["last_was_match"] = True
                    print(f"State {state_id:05d} saved")
            else:
                with lock:
                    tracking["last_was_match"] = False
                print(f"NOT IN MATCH: {screen_name}")

            time.sleep(RECORD_INTERVAL)

    except KeyboardInterrupt:
        # Record "wait" as action for last unmatched state
        with lock:
            if tracking["current_state"] is not None:
                action_path = os.path.join(ACTIONS_DIR, f"{tracking['current_state']:05d}.npy")
                np.save(action_path, np.array(WAIT_ACTION, dtype=np.int32))
                tracking["session_actions"] += 1
                print(f"Action 32 (wait) -> state {tracking['current_state']:05d} (on exit)")

        keyboard_listener.stop()
        mouse_listener.stop()
        print("\nSTOPPED")
        print(f"This session: {tracking['session_states']} states, {tracking['session_actions']} actions")
        print(f"Total recorded so far: {tracking['state_counter']} pairs")